version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" 
    schedule:
      interval: "weekly"
    groups:
      github:
        patterns:
          - "*"
