apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secretsnotifier
  namespace: appsec
spec:
  groups:
    - name: appsec
      rules:
        - alert: Naisjob failed
          expr: kube_job_failed{job_name=~"^secretsnotifier.*", namespace="appsec"} > 0
          for: 5m
          annotations:
            consequence: Secret alerts may not be discovered
            action: "check the logs"
            summary: |-
              Notifies if the latest run failed
          labels:
            namespace: appsec
            severity: warning