apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name:  secretsnotifier
  namespace: appsec
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  ttlSecondsAfterFinished: 300
  resources:
    requests:
      cpu: "100m"
      memory: 300Mi
  envFrom:
    - secret: github-security-slack-notifier
  accessPolicy:
    outbound:
      external:
        - host: console.nav.cloud.nais.io
        - host: api.github.com
        - host: slack.com

