name: Build and deploy main
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  build:
    name: Compile and test PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # ratchet:actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # ratchet:gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@243af859f8ca30903d9d7f7936897ca0358ba691 # ratchet:gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
      - name: Build and test the app
        run: ./gradlew test build



